src/Entity/Pokemon.php
<?php

namespace App\Entity;

use App\Repository\PokemonRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PokemonRepository::class)
 */
class Pokemon
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $numPokedex;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nameFr;

    /**
     * @ORM\ManyToOne(targetEntity=Types::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $type1;

    /**
     * @ORM\ManyToOne(targetEntity=Types::class)
     */
    private $type2;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $statHp;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $StatAtk;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $StatDef;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $StatSpa;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $StatSpd;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $StatSpeed;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $BST;

    /**
     * @ORM\Column(type="integer")
     */
    private $Generation;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isFinalEvol;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $catchRate;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isLegendary;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $isForm;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $height;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $weight;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumPokedex(): ?int
    {
        return $this->numPokedex;
    }

    public function setNumPokedex(int $numPokedex): self
    {
        $this->numPokedex = $numPokedex;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getNameFr(): ?string
    {
        return $this->nameFr;
    }

    public function setNameFr(?string $nameFr): self
    {
        $this->nameFr = $nameFr;

        return $this;
    }

    public function getType1(): ?Types
    {
        return $this->type1;
    }

    public function setType1(?Types $type1): self
    {
        $this->type1 = $type1;

        return $this;
    }

    public function getType2(): ?Types
    {
        return $this->type2;
    }

    public function setType2(?Types $type2): self
    {
        $this->type2 = $type2;

        return $this;
    }

    public function getStatHp(): ?int
    {
        return $this->statHp;
    }

    public function setStatHp(?int $statHp): self
    {
        $this->statHp = $statHp;

        return $this;
    }

    public function getStatAtk(): ?int
    {
        return $this->StatAtk;
    }

    public function setStatAtk(?int $StatAtk): self
    {
        $this->StatAtk = $StatAtk;

        return $this;
    }

    public function getStatDef(): ?int
    {
        return $this->StatDef;
    }

    public function setStatDef(?int $StatDef): self
    {
        $this->StatDef = $StatDef;

        return $this;
    }

    public function getStatSpa(): ?int
    {
        return $this->StatSpa;
    }

    public function setStatSpa(?int $StatSpa): self
    {
        $this->StatSpa = $StatSpa;

        return $this;
    }

    public function getStatSpd(): ?int
    {
        return $this->StatSpd;
    }

    public function setStatSpd(?int $StatSpd): self
    {
        $this->StatSpd = $StatSpd;

        return $this;
    }

    public function getStatSpeed(): ?int
    {
        return $this->StatSpeed;
    }

    public function setStatSpeed(?int $StatSpeed): self
    {
        $this->StatSpeed = $StatSpeed;

        return $this;
    }

    public function getBST(): ?int
    {
        return $this->BST;
    }

    public function setBST(?int $BST): self
    {
        $this->BST = $BST;

        return $this;
    }

    public function getGeneration(): ?int
    {
        return $this->Generation;
    }

    public function setGeneration(int $Generation): self
    {
        $this->Generation = $Generation;

        return $this;
    }

    public function isIsFinalEvol(): ?bool
    {
        return $this->isFinalEvol;
    }

    public function setIsFinalEvol(bool $isFinalEvol): self
    {
        $this->isFinalEvol = $isFinalEvol;

        return $this;
    }

    public function getCatchRate(): ?int
    {
        return $this->catchRate;
    }

    public function setCatchRate(?int $catchRate): self
    {
        $this->catchRate = $catchRate;

        return $this;
    }

    public function isIsLegendary(): ?bool
    {
        return $this->isLegendary;
    }

    public function setIsLegendary(bool $isLegendary): self
    {
        $this->isLegendary = $isLegendary;

        return $this;
    }

    public function getIsForm(): ?string
    {
        return $this->isForm;
    }

    public function setIsForm(?string $isForm): self
    {
        $this->isForm = $isForm;

        return $this;
    }

    public function getHeight(): ?float
    {
        return $this->height;
    }

    public function setHeight(?float $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getWeight(): ?float
    {
        return $this->weight;
    }

    public function setWeight(?float $weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Controller/PokemonController.php
<?php

namespace App\Controller;

use App\Entity\Pokemon;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PokemonController extends AbstractController
{

    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager) {
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/pokemon", name="app_pokemon")
     */
    public function index(): Response
    {
        return $this->render('pokemon/index.html.twig', [
            'controller_name' => 'PokemonController',
        ]);
    }

    /**
     * @Route("/pokemon/gen/{gen}", name="app_pokemon_gen")
     */
    public function gen($gen): Response
    {
        //$pokemons = $this->entityManager->getRepository(Pokemon::class)->findBy(['generation' => $gen]);
        $pokemons = $this->entityManager->getRepository(Pokemon::class)->getPokemonByGen($gen);

        if(empty($pokemons)) {
            return $this->redirectToRoute('app_pokemon_gen' ,['gen' => 1]);
        }
        return $this->render('pokemon/gen.html.twig', [
            'pokemons' => $pokemons
        ]);
    }

    /**
     * @Route("/pokemon/{id}", name="app_pokemon_show")
     */
    public function show($id): Response
    {
        $pokemon = $this->entityManager->getRepository(Pokemon::class)->findOneBy(['id' => $id]);
        return $this->render('pokemon/show.html.twig', [
            'pokemon' => $pokemon
        ]);
    }
}

templates/pokemon/gen.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PokemonController!{% endblock %}

{% block body %}

<div class="row">
    <div class="col-2"></div>
    <div class="col-8">
        <a href="{{ path('app_pokemon_gen', { 'gen' : 1 }) }}">Gen 1</a>
        <a href="{{ path('app_pokemon_gen', { 'gen' : 2 }) }}">Gen 2</a>
        <a href="{{ path('app_pokemon_gen', { 'gen' : 3 }) }}">Gen 3</a>
        <a href="{{ path('app_pokemon_gen', { 'gen' : 4 }) }}">Gen 4</a>
        <a href="{{ path('app_pokemon_gen', { 'gen' : 5 }) }}">Gen 5</a>
        <a href="{{ path('app_pokemon_gen', { 'gen' : 6 }) }}">Gen 6</a>
        <a href="{{ path('app_pokemon_gen', { 'gen' : 7 }) }}">Gen 7</a>
        <a href="{{ path('app_pokemon_gen', { 'gen' : 8 }) }}">Gen 8</a>
        <hr>
        <div class="flex">
            {% for pokemon in pokemons %}
                <a href="{{ path('app_pokemon_show', { 'id' : pokemon.id }) }}"><img src="https://img.pokemondb.net/artwork/avif/{{ pokemon.slug|lower }}.avif" alt="{{ pokemon.name }}" title="{{ pokemon.name }}" height="50"></a>
            {% endfor %}
        </div>
    </div>
    <div class="col-2"></div>
</div>


{% endblock %}

templates/pokemon/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PokemonController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/symfony/pokemonDB/src/Controller/PokemonController.php'|file_link(0) }}">src/Controller/PokemonController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/symfony/pokemonDB/templates/pokemon/index.html.twig'|file_link(0) }}">templates/pokemon/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/pokemon/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ pokemon.name }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <div class="row">
                <div class="col-4">
                    <img src="https://img.pokemondb.net/artwork/avif/{{ pokemon.slug|lower }}.avif" alt="{{ pokemon.name }}" title="{{ pokemon.name }}">
                </div>
                <div class="col-6">
                    <h1>{{ pokemon.name }}</h1>
                    <hr>
                    <div class="row">
                        <p><div class="col-3">
                            Num pokedex :
                        </div>
                        <div class="col-2">
                            {{ pokemon.numPokedex }}
                        </div></p>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-4">
                            <img src="/data/img/types/{{pokemon.type1.id}}.png" alt="{{ pokemon.type1 }}" title="{{ pokemon.type1 }}">
                        </div>
                        <div class="col-4">
                            {% if pokemon.type2 is not null %}
                                <img src="/data/img/types/{{pokemon.type2.id}}.png" alt="{{ pokemon.type2 }}" title="{{ pokemon.type2 }}">
                            {% endif %}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <p><div class="col-3">
                            Generation :
                        </div>
                        <div class="col-2">
                            {{ pokemon.generation }}
                        </div></p>
                    </div>
                    <div class="row">
                        <p><div class="col-3">
                            Base Stat Total :
                        </div>
                        <div class="col-2">
                            {{ pokemon.BST }}
                        </div></p>
                    </div>
                    <hr>
                    <div class="row">
                        <p><div class="col-3">
                            Height :
                        </div>
                        <div class="col-2">
                            {{ pokemon.height /100 }} m
                        </div></p>
                    </div>
                    <div class="row">
                        <p><div class="col-3">
                            Weight :
                        </div>
                        <div class="col-2">
                            {{ pokemon.weight /100 }} kg
                        </div></p>
                    </div>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-6">
                    <div class="row">
                        <div class="col-3">HP :</div>
                        <div class="col-1">{{ pokemon.statHp }}</div>
                        <div class="col-6">
                            <div class="progress">
                            <div class="progress-bar" role="progressbar" style="width: {{ pokemon.statHp /250 *100 }}%;"></div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">Attaque :</div>
                        <div class="col-1">{{ pokemon.statAtk }}</div>
                        <div class="col-6">
                            <div class="progress">
                            <div class="progress-bar" role="progressbar" style="width: {{ pokemon.statAtk /250 *100 }}%;"></div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">Defense :</div>
                        <div class="col-1">{{ pokemon.statDef }}</div>
                        <div class="col-6">
                            <div class="progress">
                            <div class="progress-bar" role="progressbar" style="width: {{ pokemon.statDef /250 *100 }}%;"></div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">Special Attaque :</div>
                        <div class="col-1">{{ pokemon.statSpa }}</div>
                        <div class="col-6">
                            <div class="progress">
                            <div class="progress-bar" role="progressbar" style="width: {{ pokemon.statSpa /250 *100 }}%;"></div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">Special Defense :</div>
                        <div class="col-1">{{ pokemon.statSpd }}</div>
                        <div class="col-6">
                            <div class="progress">
                            <div class="progress-bar" role="progressbar" style="width: {{ pokemon.statSpd /250 *100 }}%;"></div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">Speed :</div>
                        <div class="col-1">{{ pokemon.statSpeed }}</div>
                        <div class="col-6">
                            <div class="progress">
                            <div class="progress-bar" role="progressbar" style="width: {{ pokemon.statSpeed /250 *100 }}%;"></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-6"></div>
            </div>
        </div>
        <div class="col-2"></div>
    </div>

{% endblock %}